name: CI/CD Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "COSMOSDB_ENDPOINT=${{ secrets.COSMOSDB_ENDPOINT  }}" >> $GITHUB_ENV
        echo "COSMOSDB_KEY=${{ secrets.COSMOSDB_KEY }}" >> $GITHUB_ENV

    - name: Run test
      env:
        COSMOSDB_ENDPOINT: ${{ secrets.COSMOSDB_ENDPOINT }}
        COSMOSDB_KEY: ${{ secrets.COSMOSDB_KEY }}
      run: |
        cd My Function/test
        pytest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template
      run: |
        az deployment group create --resource-group medisha-rg --template-file Infrastructure/merged_template.json --parameters Infrastructure/merged_parameters.json
